routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use App\User;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(array('middleware' => ['admin']), function() {
    Route::get('/admin', 'AdminController@index');
    Route::resource('/admin/users', 'UserController');
    Route::resource('/admin/books', 'BookController');
    Route::get('/admin/borrow/{user}/edit/{book}','BorrowController@edit');
    Route::resource('/admin/borrow','BorrowController');
});

Route::get('/home', 'HomeController@index');
Route::resource('catalog', 'CatalogController@index');
Route::resource('basket', 'BasketController');



Route::get('/user/history', 'HomeController@history');
Route::get('/user/borrowed', 'HomeController@borrowed');
//Route::get('/user/search', 'HomeController@search');
Route::post('search', 'CatalogController@search');

/*
Route::get('/users', function () {
    $users = User::all();
    return $users;
});
Route::get('/users/{user}', function ($user) {
    $user = User::findOrFail($user);
    return $user;
});
*/

app/Http/Controllers/CatalogController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;
use App\Http\Requests;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;
class CatalogController extends Controller
{
    public function index()
    {
        $catalogs = Book::paginate(50);

        return view('catalog.index', compact('catalogs'));

    }

    public function search(Request $request )
    {
        $search=$request->input('search');
        $catalogs= Book::where('title', 'like', '%'.$search.'%')
            ->orWhere('author', 'like', '%'.$search.'%')
            ->orWhere('ISBN', 'like', '%'.$search.'%')
            ->orWhere('edition', 'like', '%'.$search.'%')
            ->orWhere('publication', 'like', '%'.$search.'%')->orderBy('title')->paginate(50);
        return view('catalog.index',['catalogs' => $catalogs]);
    }
    public function store()
    {
        //
    }

    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/catalog/index.blade.php
@extends('layouts.app')

@section('content')

    <form action="/search" method="POST" class="form-horizontal">

        <div class="form-group">
            <div class="col-md-4 col-md-offset-4">
        &nbsp;&nbsp;&nbsp;&nbsp;    <input type="text" name="search" value="" placeholder="  Szukaj..." class="form-control">
                <input type="hidden" name="_token" value="{{csrf_token()}}" >
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-4 col-md-offset-4">
                <input type="submit" value="Szukaj" class="btn btn-primary">
            </div>
        </div>

    </form>
    
    <br>

    <table class="table table-hover">
        <tr>
            <th>TYTUŁ</th>
            <th>AUTOR</th>
            <th>ISBN</th>
            <th>EDYCJA</th>
            <th>PUBLIKACJA</th>
            <th>ILOŚĆ</th>
            <th>DOSTĘPNYCH</th>
            <th>OPCJE</th>
        </tr>

        @foreach( $catalogs as $catalog)
            <tr>
                <td>{{$catalog->title}}</td>
                <td>{{$catalog->author}}</td>
                <td>{{$catalog->ISBN}}</td>
                <td>{{$catalog->edition}}</td>
                <td>{{$catalog->publication}}</td>
                <td>{{$catalog->copies}}</td>
                <td>{{$catalog->available}}</td>

                @if($catalog->available == 0)
                    <td>Brak</td>
                @else
                    <td><a href="{{ route('basket.edit',$catalog->id) }}">Wypożycz</a></td>
                @endif

            </tr>

        @endforeach


    </table>

    {{$catalogs->links() }}

@endsection