routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use App\User;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(array('middleware' => ['admin']), function() {
    Route::get('/admin', 'AdminController@index');
    Route::resource('/admin/users', 'UserController');
    Route::resource('/admin/books', 'BookController');
    Route::get('/admin/borrow/{user}/edit/{book}','BorrowController@edit');
    Route::resource('/admin/borrow','BorrowController');
});

Route::get('/home', 'HomeController@index');
Route::resource('catalog', 'CatalogController@index');
Route::resource('basket', 'BasketController');



Route::get('/user/history', 'HomeController@history');
Route::get('/user/borrowed', 'HomeController@borrowed');
//Route::get('/user/search', 'HomeController@search');
Route::post('search', 'CatalogController@search');

/*
Route::get('/users', function () {
    $users = User::all();
    return $users;
});
Route::get('/users/{user}', function ($user) {
    $user = User::findOrFail($user);
    return $user;
});
*/

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{

    public function users()
    {
        return $this->belongsToMany('App\User')->withPivot('status')
            ->withTimestamps();

        return $this->belongsToMany('App\User', 'book_user')
            ->withTimestamps();
    }



    protected $fillable = [
        'title', 'author', 'ISBN', 'edition', 'publication', 'copies', 'available'
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;

class BookController extends Controller
{
    public function index(){
        $books = Book::all();
        return view('/root/books.index')->withBooks($books);
    }

    public function create() {
        return view('/root/books.create');
    }

    public function store(Request $request) {

        $this->validate($request, [
            'title' => 'required|min:3|max:255',
            'author' => 'required|min:3|max:255',
            'ISBN' => 'required|unique:books|max:32',
            'edition' => 'required|min:3|max:255',
            'publication' => 'required|min:3|max:255',
            'copies' => 'required|numeric|min:0|max:2147483647',
            //'available' => 'required|numeric',
        ]);

        $data = $request->all();

        $book = Book::create([
            'title' => $data['title'],
            'author' => $data['author'],
            'ISBN' => $data['ISBN'],
            'edition' => $data['edition'],
            'publication' => $data['publication'],
            'copies' => $data['copies'],
            'available' => $data['copies'],
        ]);

        return redirect()->route('books.show', $book);
    }

    public function show(Book $book) {
        $books = Book::all();
        return view('/root/books.show')->withBook($book);
    }

    public function edit(Book $book) {
        return view('/root/books.edit')->withBook($book);
    }

    public function update(Request $request, Book $book) {

        $this->validate($request, [
            'title' => 'required|min:3|max:255',
            'author' => 'required|min:3|max:255',
            'ISBN' => 'required|unique:books,ISBN,'.$book->id.',id|max:32',
            'edition' => 'required|min:3|max:255',
            'publication' => 'required|min:3|max:255',
            'copies' => 'required|numeric|min:0|max:2147483647',
            'available' => 'required|numeric|min:0|max:2147483647',
        ]);

        $book->title = $request->title;
        $book->author = $request->author;
        $book->ISBN = $request->ISBN;
        $book->edition = $request->edition;
        $book->publication = $request->publication;
        $book->copies = intval($request->copies);
        if (intval($request->available) > intval($request->copies))
            $book->available = intval($request->copies);
        else
            $book->available = intval($request->available);
        $book->save();
        return redirect()->route('books.show', $book);
    }

    public function destroy(Book $book) {
        $book->delete();
        return redirect()->route('books.index');
    }
}

resources/views/root/books/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">Nowa książka</div>

                    <div class="panel-body">

                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form class="form-horizontal" action="{{route('books.store')}}" method="post">

                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Tytuł</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="title" value="{{ old('title') }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="author" class="col-md-4 control-label">Autor</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="author" value="{{ old('author') }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="ISBN" class="col-md-4 control-label">ISBN</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="ISBN" value="{{ old('ISBN') }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="edition" class="col-md-4 control-label">Wydanie</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="edition" value="{{ old('edition') }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="publication" class="col-md-4 control-label">Wydawnictwo</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="publication" value="{{ old('publication') }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="copies" class="col-md-4 control-label">Liczba kopii</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="copies" value="{{ old('copies') }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <input type="submit" value="Dodaj książkę" class="btn btn-primary">
                                    {{csrf_field()}}
                                </div>
                            </div>

                        </form>
                        <br><a href="{{ route('books.index') }}">Powrót</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/root/books/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">Edytuj książkę</div>

                    <div class="panel-body">

                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form class="form-horizontal" action="{{route('books.update', $book)}}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="form-group">
                                <label for="title" class="col-md-4 control-label">Tytuł:</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="title" value="{{ $book->title }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="author" class="col-md-4 control-label">Autor:</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="author" value="{{ $book->author }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="ISBN" class="col-md-4 control-label">ISBN:</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="ISBN" value="{{ $book->ISBN }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="edition" class="col-md-4 control-label">Wydanie:</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="edition" value="{{ $book->edition }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="publication" class="col-md-4 control-label">Wydawnictwo:</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="publication" value="{{ $book->publication }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="copies" class="col-md-4 control-label">Liczba kopii:</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="copies" value="{{ $book->copies }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="available" class="col-md-4 control-label">Dostępnych kopii:</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="available" value="{{ $book->available }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <input type="submit" value="Zapisz zmiany" class="btn btn-primary">
                                </div>
                            </div>
                        </form>
                        {{--<form class="form-horizontal" action="{{route('books.destroy',$book)}}" method="post" onSubmit="if(!confirm('Jesteś pewien, że chcesz usunąć książkę?')){return false;}">--}}
                            {{--<div class="form-group">--}}
                                {{--<div class="col-md-8 col-md-offset-4">--}}
                                    {{--<input type="submit" value="Usuń książkę" class="btn btn-primary">--}}
                                    {{--{{csrf_field()}}--}}
                                    {{--{{method_field('DELETE')}}--}}
                                {{--</div>--}}
                            {{--</div>--}}
                        {{--</form>--}}
                        <br><a href="{{ route('books.index') }}">Powrót</a>
                    </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/root/books/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">Książki</div>

                    <div class="panel-body">
                        <table class='table table-hover' wrap>
                            <th>ID</th><th>Tytuł</th><th>Autor</th><th>ISBN</th><th>Wydanie</th><th>Wydawnictwo</th><th>Kopie</th><th></th>
                            @foreach ($books as $book)
                                <tr>
                                    <td>{{ $book->id }}</td>
                                    <td>{{ $book->title }}</td>
                                    <td>{{ $book->author }}</td>
                                    <td>{{ $book->ISBN }}</td>
                                    <td>{{ $book->edition }}</td>
                                    <td>{{ $book->publication }}</td>
                                    <td>{{ $book->available }}/{{ $book->copies }}</td>
                                    <td><a href="{{ route('books.edit', $book) }}">Edytuj</a></td>
                                </tr>
                            @endforeach
                        </table>
                        <hr>
                        <a href="{{ route('books.create') }}">Dodaj nową książkę</a><br>
                        <a href="/admin">Powrót</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/root/books/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">Informacje o książce</div>

                    <div class="panel-body">
                        <h3>{{$book->author}} - {{$book->title}}</h3>
                        <b>Tytuł</b>: {{$book->title}}<br>
                        <b>Autor</b>: {{$book->author}}<br>
                        <b>ISBN</b>: {{$book->ISBN}}<br>
                        <b>Wydanie</b>: {{$book->edition}}<br>
                        <b>Wydawnictwo</b>: {{$book->publication}}<br>
                        <b>Liczba kopii</b>: {{$book->copies}}<br>
                        <b>Dostępnych kopii</b>: {{$book->available}}<br>
                        <hr>
                        <form action="{{route('books.destroy',$book)}}" method="post" onSubmit="if(!confirm('Jesteś pewien, że chcesz usunąć książkę?')){return false;}">
                            <input type="submit" value="Usuń książkę">
                            {{csrf_field()}}
                            {{method_field('DELETE')}}
                        </form>
                        <br><a href="{{ route('books.index') }}">Powrót</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection