routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use App\User;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(array('middleware' => ['admin']), function() {
    Route::get('/admin', 'AdminController@index');
    Route::resource('/admin/users', 'UserController');
    Route::resource('/admin/books', 'BookController');
    Route::get('/admin/borrow/{user}/edit/{book}','BorrowController@edit');
    Route::resource('/admin/borrow','BorrowController');
});

Route::get('/home', 'HomeController@index');
Route::resource('catalog', 'CatalogController@index');
Route::resource('basket', 'BasketController');



Route::get('/user/history', 'HomeController@history');
Route::get('/user/borrowed', 'HomeController@borrowed');
//Route::get('/user/search', 'HomeController@search');
Route::post('search', 'CatalogController@search');

/*
Route::get('/users', function () {
    $users = User::all();
    return $users;
});
Route::get('/users/{user}', function ($user) {
    $user = User::findOrFail($user);
    return $user;
});
*/

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Model;
/*<tr>
                                <td>{{ $history->title }}</td>
                                <td>{{ $history->author }}</td>
                                <td>{{ $history->created_at }}</td>
                                <td>{{ $history->updated_at }}</td>
                            </tr>*/

class User extends Authenticatable
{
    public function books()
    {
        return $this->belongsToMany('App\Book')
            ->withPivot('status')
            ->withTimestamps();

        return $this->belongsToMany('App\Book', 'book_user')
            ->withTimestamps();
    }

    public function history()
    {
        return $this->hasMany('App\History')
            ->withTimestamps();
    }
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function isAdmin() {
        return $this->admin;    // sprawdza kolumnę 'admin' w tabeli 'users'
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;


class UserController extends Controller
{
     public function index(){
         $users = User::all();
         return view('/root/users.index')->withUsers($users);
         //return view('/home');
     }

     public function create() {
         return view('/root/users.create');
     }

     public function store(Request $request) {

         $this->validate($request, [
             'name' => 'required|alpha_num|unique:users|min:3|max:32',
             'email' => 'required|email|unique:users|max:32',
             'password' => 'required|min:6|max:32',
         ]);

         $data = $request->all();

         $user = User::create([
             'name' => $data['name'],
             'email' => $data['email'],
             'password' => bcrypt($data['password']),
         ]);

         return redirect()->route('users.show', $user);
     }

     public function show(User $user) {
         $users = User::all();
         return view('/root/users.show')->withUser($user);
         //return view('users.show', ['user' => $user, 'users' => $users])->withUser($user);
     }

     public function edit(User $user) {
         return view('/root/users.edit')->withUser($user);
     }

     public function update(Request $request, User $user) {

         $this->validate($request, [
             'name' => 'required|alpha_num|min:3|max:32',
             'email' => 'required|email|unique:users,email,'.$user->id.',id|max:32',
             'admin' => 'required|boolean',
         ]);

         $user->name = $request->name;
         $user->email = $request->email;
         $user->admin = $request->admin;
         $user->save();
         return redirect()->route('users.show', $user);
     }

     public function destroy(User $user) {
         $user->delete();
         return redirect()->route('users.index');
     }
}

resources/views/root/users/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">Nowy użytkownik</div>

                    <div class="panel-body">

                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form class="form-horizontal" action="{{route('users.store')}}" method="post">

                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Nazwa</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="name" value="{{ old('name') }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="email" class="col-md-4 control-label">E-mail</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="email" value="{{ old('email') }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="Password" class="col-md-4 control-label">Hasło</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="password" value="{{ old('password') }}">
                                </div>
                            </div>

                            {{--<label for="admin">Admin</label>--}}
                            {{--<input type="text" name="admin" value="{{ old('admin') }}">--}}

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <input type="submit" value="Dodaj użytkownika" class="btn btn-primary">
                                    {{csrf_field()}}
                                </div>
                            </div>
                        </form>
                        <br><a href="{{ route('users.index') }}">Powrót</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/root/users/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">Edytuj użytkownika</div>

                    <div class="panel-body">

                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form class="form-horizontal" action="{{route('users.update', $user)}}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Nazwa:</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="name" value="{{ $user->name }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="email" class="col-md-4 control-label">E-mail:</label>
                                <div class="col-md-6">
                                    <input class="form-control" type="text" name="email" value="{{ $user->email }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="admin"  class="col-md-4 control-label">Rola:</label>
                                <div class="col-md-6">
                                    <select name="admin" class="col-md-4 control-label">
                                        <option value="0" @php if ($user->admin == 0) echo "selected"; @endphp>user</option>
                                        <option value="1" @php if ($user->admin == 1) echo "selected"; @endphp>admin</option>
                                    </select>
                                    {{--<input type="text" name="admin" value="{{ $user->admin }}"><br>--}}
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <input type="submit" value="Zapisz zmiany" class="btn btn-primary">
                                </div>
                            </div>
                        </form>

                        <form class="form-horizontal" action="{{route('users.destroy',$user)}}" method="post" onSubmit="if(!confirm('Jesteś pewien, że chcesz usunąć użytkownika?')){return false;}">
                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <input type="submit" value="Usuń użytkownika" class="btn btn-primary">
                                    {{csrf_field()}}
                                    {{method_field('DELETE')}}
                                </div>
                            </div>
                        </form>
                        <br><a href="{{ route('users.index') }}">Powrót</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/root/users/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">Użytkownicy</div>

                    <div class="panel-body">
                        <table class='table table-hover'>
                            <th>ID</th><th>Nazwa użytkownika</th><th>E-mail</th><th>Info</th><th></th>
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>
                                        @if ($user->admin)
                                            admin
                                        @else
                                            user
                                        @endif
                                    </td>
                                    <td><a href="{{ route('users.edit', $user) }}">Edytuj</a></td>
                                </tr>
                            @endforeach
                        </table>
                        <hr>
                        <a href="{{ route('users.create') }}">Dodaj nowego użytkownika</a><br>
                        <a href="/admin">Powrót</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/root/users/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">

                    <div class="panel-heading">Informacje o użytkowniku</div>

                    <div class="panel-body">
                        <h3>{{$user->name}}</h3>
                        <table class='table table-hover'>
                            <th>ID</th><th>Nazwa użytkownika</th><th>E-mail</th><th>Info</th><th></th>
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    @if ($user->admin)
                                        admin
                                    @else
                                        user
                                    @endif
                                </td>
                                <td><a href="{{ route('users.edit', $user) }}">Edytuj</a></td>
                            </tr>
                        </table>
                        <hr>
                        <form action="{{route('users.destroy',$user)}}" method="post" onSubmit="if(!confirm('Jesteś pewien, że chcesz usunąć tego użytkownika?')){return false;}">
                            <input type="submit" value="Usuń użytkownika">
                            {{csrf_field()}}
                            {{method_field('DELETE')}}
                        </form>
                        <br><a href="{{ route('users.index') }}">Powrót</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection